'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ip1() As String
            Get
                Return CType(Me("ip1"),String)
            End Get
            Set
                Me("ip1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ip2() As String
            Get
                Return CType(Me("ip2"),String)
            End Get
            Set
                Me("ip2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ip3() As String
            Get
                Return CType(Me("ip3"),String)
            End Get
            Set
                Me("ip3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ip4() As String
            Get
                Return CType(Me("ip4"),String)
            End Get
            Set
                Me("ip4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ico1() As String
            Get
                Return CType(Me("ico1"),String)
            End Get
            Set
                Me("ico1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ico2() As String
            Get
                Return CType(Me("ico2"),String)
            End Get
            Set
                Me("ico2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ico3() As String
            Get
                Return CType(Me("ico3"),String)
            End Get
            Set
                Me("ico3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ico4() As String
            Get
                Return CType(Me("ico4"),String)
            End Get
            Set
                Me("ico4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property psw_antitheft() As String
            Get
                Return CType(Me("psw_antitheft"),String)
            End Get
            Set
                Me("psw_antitheft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1354")>  _
        Public Property chieungang() As String
            Get
                Return CType(Me("chieungang"),String)
            End Get
            Set
                Me("chieungang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("721")>  _
        Public Property chieudoc() As String
            Get
                Return CType(Me("chieudoc"),String)
            End Get
            Set
                Me("chieudoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property phongto() As String
            Get
                Return CType(Me("phongto"),String)
            End Get
            Set
                Me("phongto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property thunho() As String
            Get
                Return CType(Me("thunho"),String)
            End Get
            Set
                Me("thunho") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property anhnen() As String
            Get
                Return CType(Me("anhnen"),String)
            End Get
            Set
                Me("anhnen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property anhnendefault() As String
            Get
                Return CType(Me("anhnendefault"),String)
            End Get
            Set
                Me("anhnendefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("19")>  _
        Public Property ten1y() As String
            Get
                Return CType(Me("ten1y"),String)
            End Get
            Set
                Me("ten1y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("429")>  _
        Public Property ten1x() As String
            Get
                Return CType(Me("ten1x"),String)
            End Get
            Set
                Me("ten1x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("182")>  _
        Public Property ten2y() As String
            Get
                Return CType(Me("ten2y"),String)
            End Get
            Set
                Me("ten2y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("596")>  _
        Public Property ten2x() As String
            Get
                Return CType(Me("ten2x"),String)
            End Get
            Set
                Me("ten2x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("464")>  _
        Public Property ten3y() As String
            Get
                Return CType(Me("ten3y"),String)
            End Get
            Set
                Me("ten3y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("759")>  _
        Public Property ten3x() As String
            Get
                Return CType(Me("ten3x"),String)
            End Get
            Set
                Me("ten3x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("891")>  _
        Public Property ten4x() As String
            Get
                Return CType(Me("ten4x"),String)
            End Get
            Set
                Me("ten4x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("536")>  _
        Public Property ten4y() As String
            Get
                Return CType(Me("ten4y"),String)
            End Get
            Set
                Me("ten4y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("265")>  _
        Public Property time1x() As String
            Get
                Return CType(Me("time1x"),String)
            End Get
            Set
                Me("time1x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("88")>  _
        Public Property time1y() As String
            Get
                Return CType(Me("time1y"),String)
            End Get
            Set
                Me("time1y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("428")>  _
        Public Property time2x() As String
            Get
                Return CType(Me("time2x"),String)
            End Get
            Set
                Me("time2x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("252")>  _
        Public Property time2y() As String
            Get
                Return CType(Me("time2y"),String)
            End Get
            Set
                Me("time2y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("595")>  _
        Public Property time3x() As String
            Get
                Return CType(Me("time3x"),String)
            End Get
            Set
                Me("time3x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("431")>  _
        Public Property time3y() As String
            Get
                Return CType(Me("time3y"),String)
            End Get
            Set
                Me("time3y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("721")>  _
        Public Property time4x() As String
            Get
                Return CType(Me("time4x"),String)
            End Get
            Set
                Me("time4x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
        Public Property time4y() As String
            Get
                Return CType(Me("time4y"),String)
            End Get
            Set
                Me("time4y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("410")>  _
        Public Property dapan1x() As String
            Get
                Return CType(Me("dapan1x"),String)
            End Get
            Set
                Me("dapan1x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("82")>  _
        Public Property dapan1y() As String
            Get
                Return CType(Me("dapan1y"),String)
            End Get
            Set
                Me("dapan1y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("566")>  _
        Public Property dapan2x() As String
            Get
                Return CType(Me("dapan2x"),String)
            End Get
            Set
                Me("dapan2x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("246")>  _
        Public Property dapan2y() As String
            Get
                Return CType(Me("dapan2y"),String)
            End Get
            Set
                Me("dapan2y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("737")>  _
        Public Property dapan3x() As String
            Get
                Return CType(Me("dapan3x"),String)
            End Get
            Set
                Me("dapan3x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("425")>  _
        Public Property dapan3y() As String
            Get
                Return CType(Me("dapan3y"),String)
            End Get
            Set
                Me("dapan3y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("857")>  _
        Public Property dapan4x() As String
            Get
                Return CType(Me("dapan4x"),String)
            End Get
            Set
                Me("dapan4x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("594")>  _
        Public Property dapan4y() As String
            Get
                Return CType(Me("dapan4y"),String)
            End Get
            Set
                Me("dapan4y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property mautieudemnt() As Global.System.Drawing.Color
            Get
                Return CType(Me("mautieudemnt"),Global.System.Drawing.Color)
            End Get
            Set
                Me("mautieudemnt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property maunoidungmnt() As Global.System.Drawing.Color
            Get
                Return CType(Me("maunoidungmnt"),Global.System.Drawing.Color)
            End Get
            Set
                Me("maunoidungmnt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property anti() As String
            Get
                Return CType(Me("anti"),String)
            End Get
            Set
                Me("anti") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property mautexttieude() As Global.System.Drawing.Color
            Get
                Return CType(Me("mautexttieude"),Global.System.Drawing.Color)
            End Get
            Set
                Me("mautexttieude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property mautextnoidung() As Global.System.Drawing.Color
            Get
                Return CType(Me("mautextnoidung"),Global.System.Drawing.Color)
            End Get
            Set
                Me("mautextnoidung") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property boldtieude() As String
            Get
                Return CType(Me("boldtieude"),String)
            End Get
            Set
                Me("boldtieude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property boldnoidung() As String
            Get
                Return CType(Me("boldnoidung"),String)
            End Get
            Set
                Me("boldnoidung") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("1")> _
        Public Property ktrabq() As Integer
            Get
                Return CType(Me("ktrabq"), Integer)
            End Get
            Set(value As Integer)
                Me("ktrabq") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property s() As String
            Get
                Return CType(Me("s"), String)
            End Get
            Set(value As String)
                Me("s") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property ưqeqưe() As Integer
            Get
                Return CType(Me("ưqeqưe"), Integer)
            End Get
            Set(value As Integer)
                Me("ưqeqưe") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("2")> _
        Public Property keyanh() As Integer
            Get
                Return CType(Me("keyanh"), Integer)
            End Get
            Set(value As Integer)
                Me("keyanh") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property keyanh2() As String
            Get
                Return CType(Me("keyanh2"), String)
            End Get
            Set(value As String)
                Me("keyanh2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("2")> _
        Public Property ddd() As Integer
            Get
                Return CType(Me("ddd"), Integer)
            End Get
            Set(value As Integer)
                Me("ddd") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CPONH.My.MySettings
            Get
                Return Global.CPONH.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
